jdk:
  - openjdk8
before_install:
  - sdk install java 8.0.292-open
  - sdk use java 8.0.292-open
  - sdk install gradle 6.8.3
  - sdk use gradle 6.8.3
install:
  - ./gradlew :library:assemble
  - ./gradlew :library:assembleRelease